# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.
color_theme = "ocean"
# Enable users to switch between day and night mode?
day_night = false

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "classic"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Glenn Fiedler's game development and networking articles"

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = "gafferongames"

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

############################
## Contact Widget setup   ##
############################

# Contact links
contact_links = [ {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"} ]

############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = []
plugins_js  = []

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Align the main menu to the right of the page? (true/false)
menu_align_right = true

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = false
